// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/tin/proto/tin.proto

package tin_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetTinRequest struct {
	Tin                  string   `protobuf:"bytes,1,opt,name=tin,proto3" json:"tin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTinRequest) Reset()         { *m = GetTinRequest{} }
func (m *GetTinRequest) String() string { return proto.CompactTextString(m) }
func (*GetTinRequest) ProtoMessage()    {}
func (*GetTinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e4a2011a61ffae7, []int{0}
}

func (m *GetTinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTinRequest.Unmarshal(m, b)
}
func (m *GetTinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTinRequest.Marshal(b, m, deterministic)
}
func (m *GetTinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTinRequest.Merge(m, src)
}
func (m *GetTinRequest) XXX_Size() int {
	return xxx_messageInfo_GetTinRequest.Size(m)
}
func (m *GetTinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTinRequest proto.InternalMessageInfo

func (m *GetTinRequest) GetTin() string {
	if m != nil {
		return m.Tin
	}
	return ""
}

type GetTinResponse struct {
	Tin                  string   `protobuf:"bytes,1,opt,name=tin,proto3" json:"tin,omitempty"`
	Tgrc                 string   `protobuf:"bytes,2,opt,name=tgrc,proto3" json:"tgrc,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	FCs                  string   `protobuf:"bytes,4,opt,name=FCs,proto3" json:"FCs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTinResponse) Reset()         { *m = GetTinResponse{} }
func (m *GetTinResponse) String() string { return proto.CompactTextString(m) }
func (*GetTinResponse) ProtoMessage()    {}
func (*GetTinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e4a2011a61ffae7, []int{1}
}

func (m *GetTinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTinResponse.Unmarshal(m, b)
}
func (m *GetTinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTinResponse.Marshal(b, m, deterministic)
}
func (m *GetTinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTinResponse.Merge(m, src)
}
func (m *GetTinResponse) XXX_Size() int {
	return xxx_messageInfo_GetTinResponse.Size(m)
}
func (m *GetTinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTinResponse proto.InternalMessageInfo

func (m *GetTinResponse) GetTin() string {
	if m != nil {
		return m.Tin
	}
	return ""
}

func (m *GetTinResponse) GetTgrc() string {
	if m != nil {
		return m.Tgrc
	}
	return ""
}

func (m *GetTinResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetTinResponse) GetFCs() string {
	if m != nil {
		return m.FCs
	}
	return ""
}

func init() {
	proto.RegisterType((*GetTinRequest)(nil), "tin.GetTinRequest")
	proto.RegisterType((*GetTinResponse)(nil), "tin.GetTinResponse")
}

func init() {
	proto.RegisterFile("internal/tin/proto/tin.proto", fileDescriptor_7e4a2011a61ffae7)
}

var fileDescriptor_7e4a2011a61ffae7 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x31, 0x4b, 0x03, 0x41,
	0x10, 0x85, 0x49, 0x2e, 0x8a, 0x0e, 0x2a, 0x32, 0x5a, 0x1c, 0x21, 0x85, 0x5e, 0x65, 0x75, 0x0b,
	0x5a, 0xda, 0x25, 0x90, 0xb4, 0x12, 0x53, 0x59, 0x28, 0x9b, 0x30, 0x1c, 0x03, 0xc7, 0xec, 0xba,
	0x3b, 0xda, 0x88, 0x8d, 0x7f, 0xc1, 0x9f, 0xe6, 0x5f, 0xf0, 0x87, 0xc8, 0xee, 0x62, 0x71, 0xa4,
	0xfb, 0xe6, 0xf1, 0x1e, 0xbc, 0x37, 0x30, 0x63, 0x51, 0x0a, 0x62, 0x7b, 0xa3, 0x2c, 0xc6, 0x07,
	0xa7, 0x2e, 0x51, 0x9b, 0x09, 0x2b, 0x65, 0x99, 0xce, 0x3a, 0xe7, 0xba, 0x9e, 0x8c, 0xf5, 0x6c,
	0xac, 0x88, 0x53, 0xab, 0xec, 0x24, 0x16, 0x4b, 0x73, 0x0d, 0xa7, 0x2b, 0xd2, 0x0d, 0xcb, 0x9a,
	0x5e, 0xdf, 0x28, 0x2a, 0x9e, 0x43, 0x4a, 0xd5, 0xa3, 0xab, 0xd1, 0xcd, 0xf1, 0x3a, 0x61, 0xf3,
	0x0c, 0x67, 0xff, 0x96, 0xe8, 0x9d, 0x44, 0xda, 0xf7, 0x20, 0xc2, 0x44, 0xbb, 0xb0, 0xab, 0xc7,
	0x59, 0xca, 0x8c, 0x97, 0x70, 0xa0, 0xac, 0x3d, 0xd5, 0x55, 0x16, 0xcb, 0x91, 0xb2, 0xcb, 0x45,
	0xac, 0x27, 0x25, 0xbb, 0x5c, 0xc4, 0xdb, 0x07, 0x80, 0x0d, 0xcb, 0x23, 0x85, 0x77, 0xde, 0x11,
	0xce, 0xa1, 0x5a, 0x91, 0x22, 0xb6, 0x69, 0xc6, 0xa0, 0xda, 0xf4, 0x62, 0xa0, 0x95, 0x2e, 0x0d,
	0x7e, 0xfd, 0xfc, 0x7e, 0x8f, 0x4f, 0x10, 0xf2, 0x07, 0x3e, 0x94, 0xe5, 0x73, 0x0e, 0x4f, 0x47,
	0xed, 0xbd, 0xb2, 0xbc, 0xf8, 0xed, 0xf6, 0x30, 0xef, 0xbc, 0xfb, 0x0b, 0x00, 0x00, 0xff, 0xff,
	0xea, 0xaa, 0x31, 0x06, 0x2a, 0x01, 0x00, 0x00,
}
